Feat/search UI Comparison
malkoG/YiMattHong pull request #27
Opened 2021-12-07 14:13 UTC by heeboy007

Added search bar at top.
Before :
![before](https://user-images.githubusercontent.com/41155496/145044488-abf71eba-aaa1-4773-a757-f4e98c80f11b.JPG)
After :
![after](https://user-images.githubusercontent.com/41155496/145044498-4487ae5a-a935-4c47-8d59-1ad000f11e89.JPG)
Also, new view called search is added :
![new](https://user-images.githubusercontent.com/41155496/145044502-71f4d979-7b60-4240-9ec1-ca478fa772e0.JPG)

2021-12-09 08:45 UTC, malkoG commented on app/finder/notice_finder.rb
> +    Board.includes(:notices).find(@params[:id]).notices
klass라고 하기에는 클래스를 나타내는 표현이 아니네요.
`aggregation`이나 `subquery` 같은게 올바른 표현이 아닌가 싶은 생각이 듭니다.

2021-12-09 08:45 UTC, malkoG commented on app/finder/notice_finder.rb
> +    .where("lower(title) LIKE :search", search: "%#{@params[:search]}")
참고로 말씀드리자면, LIKE 매칭은 탐색 속도가 느린 편이기도 하고, 그 글자가 완전히 매칭되지 않으면 제대로 검색되지 않는 문제점이 있습니다. 차라리 로마자표기법으로 변환해서 Trigram Full text search를 하는게 가장 정확할거에요.

이건 개선사항이라기보다는 참고하시라고 코멘트 남겨둡니다.
구현의 난이도가 높을 수 있으니 이건 제가 따로 수습해볼게요.

2021-12-09 08:48 UTC, malkoG commented
그리고 Before/After는 가독성을 위해 테이블 문법을 이용해서 나타내는 것을 적극 권장합니다.

|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/41155496/145044488-abf71eba-aaa1-4773-a757-f4e98c80f11b.JPG)|![after](https://user-images.githubusercontent.com/41155496/145044498-4487ae5a-a935-4c47-8d59-1ad000f11e89.JPG)|


이런 식으로요

2021-12-11 18:06 UTC, malkoG requested changes
프로덕션에서 발생한 에러에 대한 픽스가 아니면 어지간하면 squash해주시면 좋습니다. main 브랜치 기준으로는 불필요한 커밋이 보이지 않도록 브랜치를 깔끔하게 관리하면 좋아요.

2021-12-11 18:07 UTC, malkoG requested changes

2021-12-11 18:07 UTC, malkoG commented on spec/requests/search_request_spec.rb
> +      get search_path, params: { id: '31', page: '1', search: 'test notice 01' }
factory bot으로 인스턴스를 먼저 만들어줘야 하지 않나요?

2021-12-11 18:10 UTC, malkoG commented
커밋메세지는 **명령조** 로 작성하시는게 좋습니다.

https://meetup.toast.com/posts/106

2021-12-14 11:33 UTC, heeboy007 commented on spec/requests/search_request_spec.rb
> +      get search_path, params: { id: '31', page: '1', search: 'test notice 01' }
인스턴스 작성해서 커밋했습니다!

2021-12-24 02:12 UTC, malkoG commented
* 수정 사항 1 : 검색페이지 / 공지사항 리스트 페이지 이렇게 분리할거면 그냥 합치는게 좋아요.

커뮤니티 사이트 많이 이용해보셨으면 어떤 느낌인지 아실 것이라 생각합니다.

* 수정 사항 2 : **테스트**와 **수정 및 기능 추가**는 한 커밋에 페어로 맞춰주는게 좋아요.

* 수정 사항 3 : UI/UX는 가능하면 신경써주시면 좋습니다.

2021-12-24 02:14 UTC, malkoG commented
UI 수정 결과 스크린샷

![Deepin스크린샷_선택 영역_20211224111334](https://user-images.githubusercontent.com/2427963/147307398-09789793-45e7-4b2e-8837-9be005c2567f.png)
![Deepin스크린샷_선택 영역_20211224111320](https://user-images.githubusercontent.com/2427963/147307402-a7dd62a9-1fed-4ef2-a62c-98453dcaed00.png)

2021-12-24 19:30 UTC, malkoG commented
![Deepin스크린샷_선택 영역_20211225034004](https://user-images.githubusercontent.com/2427963/147370228-847c61a1-3c03-49ce-8867-aa04a3dab115.png)

Full text search 적용 예

2021-12-24 19:31 UTC, merged